version: '3.9'
services:
  nginx:
    container_name: kmz-brno-solari-nginx
    ports:
      - 8000:80
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.php:/var/www/html/index.php
      - ./style.css:/var/www/html/style.css
      - ./data.json:/var/www/html/data.json
  php:
    container_name: kmz-brno-solari-php
    image: php:fpm-alpine
    volumes:
      - ./index.php:/var/www/html/index.php  
      - ./style.css:/var/www/html/style.css
      - ./data.json:/var/www/html/data.json